// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-blog/app/blog/internal/biz"
	"kratos-blog/app/blog/internal/conf"
	"kratos-blog/app/blog/internal/data"
	"kratos-blog/app/blog/internal/server"
	"kratos-blog/app/blog/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data,registry *conf.Registry,logger log.Logger) (*kratos.App, func(), error) {
	r := data.NewRegistrar(registry)
	db := data.NewDB(confData)
	rdb := data.NewRDB(confData)
	dataData, err := data.NewData(confData, logger,db,rdb)
	if err != nil {
		return nil, nil, err
	}
	blogRepo := data.NewBlogRepo(dataData, logger)
	blogUsecase := biz.NewBlogUseCase(blogRepo, logger)
	blogService := service.NewBlogService(blogUsecase)
	grpcServer := server.NewGRPCServer(confServer, blogService, logger)
	httpServer := server.NewHTTPServer(confServer, blogService, logger)
	app := newApp(logger, grpcServer, httpServer,r)
	return app, func() {
	}, nil
}
