// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-blog/app/user/internal/biz"
	"kratos-blog/app/user/internal/conf"
	"kratos-blog/app/user/internal/data"
	"kratos-blog/app/user/internal/server"
	"kratos-blog/app/user/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Bootstrap,registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	r := data.NewRegistrar(registry)
	db := data.NewDB(confData.Data)
	rdb := data.NewRDB(confData.Data)
	dataData, err := data.NewData(confData, logger,db,rdb)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUseCase(userRepo,confData,logger)
	userService := service.NewUserService(userUsecase)
	grpcServer := server.NewGRPCServer(confServer, userService, logger)
	httpServer := server.NewHTTPServer(confServer, userService, logger)
	app := newApp(logger, grpcServer, httpServer,r)
	return app, func() {
	}, nil
}
