// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.1
// - protoc             v4.25.1
// source: blog.proto

package blog
import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationBlogAddSuggestBlog = "/api.v1.Blog/AddSuggestBlog"
const OperationBlogCacheBlog = "/api.v1.Blog/CacheBlog"
const OperationBlogCreateBlog = "/api.v1.Blog/CreateBlog"
const OperationBlogDeleteBlog = "/api.v1.Blog/DeleteBlog"
const OperationBlogDeleteCacheBlog = "/api.v1.Blog/DeleteCacheBlog"
const OperationBlogDeleteSuggestBlog = "/api.v1.Blog/DeleteSuggestBlog"
const OperationBlogGetAllSuggest = "/api.v1.Blog/GetAllSuggest"
const OperationBlogGetBlogByID = "/api.v1.Blog/GetBlogByID"
const OperationBlogGetBlogByTag = "/api.v1.Blog/GetBlogByTag"
const OperationBlogGetBlogByTitle = "/api.v1.Blog/GetBlogByTitle"
const OperationBlogGetCacheBlog = "/api.v1.Blog/GetCacheBlog"
const OperationBlogListBlog = "/api.v1.Blog/ListBlog"
const OperationBlogUpdateBlog = "/api.v1.Blog/UpdateBlog"
const OperationBlogUpdateIndividualFields = "/api.v1.Blog/UpdateIndividualFields"
const OperationBlogUpdateOnly = "/api.v1.Blog/UpdateOnly"

type BlogHTTPServer interface {
	AddSuggestBlog(context.Context, *SuggestBlogRequest) (*SuggestBlogReply, error)
	CacheBlog(context.Context, *CreateBlogRequest) (*CreateBlogReply, error)
	CreateBlog(context.Context, *CreateBlogRequest) (*CreateBlogReply, error)
	DeleteBlog(context.Context, *DeleteBlogRequest) (*DeleteBlogReply, error)
	DeleteCacheBlog(context.Context, *DeleteCacheBlogRequest) (*DeleteCacheBlogReply, error)
	DeleteSuggestBlog(context.Context, *SuggestBlogRequest) (*SuggestBlogReply, error)
	GetAllSuggest(context.Context, *SearchAllSuggest) (*SearchAllReply, error)
	GetBlogByID(context.Context, *GetBlogIDRequest) (*GetBlogIDReply, error)
	GetBlogByTag(context.Context, *GetBlogRequest) (*GetBlogReply, error)
	GetBlogByTitle(context.Context, *GetBlogByTitleRequest) (*GetBlogByTitleReply, error)
	GetCacheBlog(context.Context, *ListBlogRequest) (*ListCacheReply, error)
	ListBlog(context.Context, *ListBlogRequest) (*ListBlogReply, error)
	UpdateBlog(context.Context, *UpdateBlogRequest) (*UpdateBlogReply, error)
	UpdateIndividualFields(context.Context, *UpdateIndividualFieldsRequest) (*UpdateIndividualFieldsReply, error)
	UpdateOnly(context.Context, *UpdateOnlyRequest) (*UpdateOnlyReply, error)
}

func RegisterBlogHTTPServer(s *http.Server, srv BlogHTTPServer) {
	r := s.Route("/")
	r.POST("/api/addBlog", _Blog_CreateBlog0_HTTP_Handler(srv))
	r.PUT("/api/updateBlog/{id}", _Blog_UpdateBlog0_HTTP_Handler(srv))
	r.PUT("/api/updateIndividual", _Blog_UpdateIndividualFields0_HTTP_Handler(srv))
	r.DELETE("/api/deleteBlog/{id}/{key}", _Blog_DeleteBlog0_HTTP_Handler(srv))
	r.GET("/api/getTagName/{tag}", _Blog_GetBlogByTag0_HTTP_Handler(srv))
	r.GET("/api/getAllBlog", _Blog_ListBlog0_HTTP_Handler(srv))
	r.GET("/api/getId/{id}", _Blog_GetBlogByID0_HTTP_Handler(srv))
	r.GET("/api/searchBlog/{title}", _Blog_GetBlogByTitle0_HTTP_Handler(srv))
	r.PUT("/api/updateOnly", _Blog_UpdateOnly0_HTTP_Handler(srv))
	r.POST("/api/cacheBlog", _Blog_CacheBlog0_HTTP_Handler(srv))
	r.GET("/api/getCacheBlog", _Blog_GetCacheBlog0_HTTP_Handler(srv))
	r.DELETE("/api/deleteCacheBlog", _Blog_DeleteCacheBlog0_HTTP_Handler(srv))
	r.POST("/api/addSuggest", _Blog_AddSuggestBlog0_HTTP_Handler(srv))
	r.DELETE("/api/deleteSuggest/{id}", _Blog_DeleteSuggestBlog0_HTTP_Handler(srv))
	r.GET("/api/getAllSuggest", _Blog_GetAllSuggest0_HTTP_Handler(srv))
}

func _Blog_CreateBlog0_HTTP_Handler(srv BlogHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateBlogRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBlogCreateBlog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateBlog(ctx, req.(*CreateBlogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateBlogReply)
		return ctx.Result(200, reply)
	}
}

func _Blog_UpdateBlog0_HTTP_Handler(srv BlogHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateBlogRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBlogUpdateBlog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateBlog(ctx, req.(*UpdateBlogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateBlogReply)
		return ctx.Result(200, reply)
	}
}

func _Blog_UpdateIndividualFields0_HTTP_Handler(srv BlogHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateIndividualFieldsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBlogUpdateIndividualFields)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateIndividualFields(ctx, req.(*UpdateIndividualFieldsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateIndividualFieldsReply)
		return ctx.Result(200, reply)
	}
}

func _Blog_DeleteBlog0_HTTP_Handler(srv BlogHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteBlogRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBlogDeleteBlog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteBlog(ctx, req.(*DeleteBlogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteBlogReply)
		return ctx.Result(200, reply)
	}
}

func _Blog_GetBlogByTag0_HTTP_Handler(srv BlogHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetBlogRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBlogGetBlogByTag)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBlogByTag(ctx, req.(*GetBlogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetBlogReply)
		return ctx.Result(200, reply)
	}
}

func _Blog_ListBlog0_HTTP_Handler(srv BlogHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListBlogRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBlogListBlog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListBlog(ctx, req.(*ListBlogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListBlogReply)
		return ctx.Result(200, reply)
	}
}

func _Blog_GetBlogByID0_HTTP_Handler(srv BlogHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetBlogIDRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBlogGetBlogByID)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBlogByID(ctx, req.(*GetBlogIDRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetBlogIDReply)
		return ctx.Result(200, reply)
	}
}

func _Blog_GetBlogByTitle0_HTTP_Handler(srv BlogHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetBlogByTitleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBlogGetBlogByTitle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBlogByTitle(ctx, req.(*GetBlogByTitleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetBlogByTitleReply)
		return ctx.Result(200, reply)
	}
}

func _Blog_UpdateOnly0_HTTP_Handler(srv BlogHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateOnlyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBlogUpdateOnly)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateOnly(ctx, req.(*UpdateOnlyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateOnlyReply)
		return ctx.Result(200, reply)
	}
}

func _Blog_CacheBlog0_HTTP_Handler(srv BlogHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateBlogRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBlogCacheBlog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CacheBlog(ctx, req.(*CreateBlogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateBlogReply)
		return ctx.Result(200, reply)
	}
}

func _Blog_GetCacheBlog0_HTTP_Handler(srv BlogHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListBlogRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBlogGetCacheBlog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCacheBlog(ctx, req.(*ListBlogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCacheReply)
		return ctx.Result(200, reply)
	}
}

func _Blog_DeleteCacheBlog0_HTTP_Handler(srv BlogHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteCacheBlogRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBlogDeleteCacheBlog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteCacheBlog(ctx, req.(*DeleteCacheBlogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteCacheBlogReply)
		return ctx.Result(200, reply)
	}
}

func _Blog_AddSuggestBlog0_HTTP_Handler(srv BlogHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SuggestBlogRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBlogAddSuggestBlog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddSuggestBlog(ctx, req.(*SuggestBlogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SuggestBlogReply)
		return ctx.Result(200, reply)
	}
}

func _Blog_DeleteSuggestBlog0_HTTP_Handler(srv BlogHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SuggestBlogRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBlogDeleteSuggestBlog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteSuggestBlog(ctx, req.(*SuggestBlogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SuggestBlogReply)
		return ctx.Result(200, reply)
	}
}

func _Blog_GetAllSuggest0_HTTP_Handler(srv BlogHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SearchAllSuggest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBlogGetAllSuggest)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAllSuggest(ctx, req.(*SearchAllSuggest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SearchAllReply)
		return ctx.Result(200, reply)
	}
}

type BlogHTTPClient interface {
	AddSuggestBlog(ctx context.Context, req *SuggestBlogRequest, opts ...http.CallOption) (rsp *SuggestBlogReply, err error)
	CacheBlog(ctx context.Context, req *CreateBlogRequest, opts ...http.CallOption) (rsp *CreateBlogReply, err error)
	CreateBlog(ctx context.Context, req *CreateBlogRequest, opts ...http.CallOption) (rsp *CreateBlogReply, err error)
	DeleteBlog(ctx context.Context, req *DeleteBlogRequest, opts ...http.CallOption) (rsp *DeleteBlogReply, err error)
	DeleteCacheBlog(ctx context.Context, req *DeleteCacheBlogRequest, opts ...http.CallOption) (rsp *DeleteCacheBlogReply, err error)
	DeleteSuggestBlog(ctx context.Context, req *SuggestBlogRequest, opts ...http.CallOption) (rsp *SuggestBlogReply, err error)
	GetAllSuggest(ctx context.Context, req *SearchAllSuggest, opts ...http.CallOption) (rsp *SearchAllReply, err error)
	GetBlogByID(ctx context.Context, req *GetBlogIDRequest, opts ...http.CallOption) (rsp *GetBlogIDReply, err error)
	GetBlogByTag(ctx context.Context, req *GetBlogRequest, opts ...http.CallOption) (rsp *GetBlogReply, err error)
	GetBlogByTitle(ctx context.Context, req *GetBlogByTitleRequest, opts ...http.CallOption) (rsp *GetBlogByTitleReply, err error)
	GetCacheBlog(ctx context.Context, req *ListBlogRequest, opts ...http.CallOption) (rsp *ListCacheReply, err error)
	ListBlog(ctx context.Context, req *ListBlogRequest, opts ...http.CallOption) (rsp *ListBlogReply, err error)
	UpdateBlog(ctx context.Context, req *UpdateBlogRequest, opts ...http.CallOption) (rsp *UpdateBlogReply, err error)
	UpdateIndividualFields(ctx context.Context, req *UpdateIndividualFieldsRequest, opts ...http.CallOption) (rsp *UpdateIndividualFieldsReply, err error)
	UpdateOnly(ctx context.Context, req *UpdateOnlyRequest, opts ...http.CallOption) (rsp *UpdateOnlyReply, err error)
}

type BlogHTTPClientImpl struct {
	cc *http.Client
}

func NewBlogHTTPClient(client *http.Client) BlogHTTPClient {
	return &BlogHTTPClientImpl{client}
}

func (c *BlogHTTPClientImpl) AddSuggestBlog(ctx context.Context, in *SuggestBlogRequest, opts ...http.CallOption) (*SuggestBlogReply, error) {
	var out SuggestBlogReply
	pattern := "/api/addSuggest"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBlogAddSuggestBlog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BlogHTTPClientImpl) CacheBlog(ctx context.Context, in *CreateBlogRequest, opts ...http.CallOption) (*CreateBlogReply, error) {
	var out CreateBlogReply
	pattern := "/api/cacheBlog"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBlogCacheBlog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BlogHTTPClientImpl) CreateBlog(ctx context.Context, in *CreateBlogRequest, opts ...http.CallOption) (*CreateBlogReply, error) {
	var out CreateBlogReply
	pattern := "/api/addBlog"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBlogCreateBlog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BlogHTTPClientImpl) DeleteBlog(ctx context.Context, in *DeleteBlogRequest, opts ...http.CallOption) (*DeleteBlogReply, error) {
	var out DeleteBlogReply
	pattern := "/api/deleteBlog/{id}/{key}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBlogDeleteBlog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BlogHTTPClientImpl) DeleteCacheBlog(ctx context.Context, in *DeleteCacheBlogRequest, opts ...http.CallOption) (*DeleteCacheBlogReply, error) {
	var out DeleteCacheBlogReply
	pattern := "/api/deleteCacheBlog"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBlogDeleteCacheBlog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BlogHTTPClientImpl) DeleteSuggestBlog(ctx context.Context, in *SuggestBlogRequest, opts ...http.CallOption) (*SuggestBlogReply, error) {
	var out SuggestBlogReply
	pattern := "/api/deleteSuggest/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBlogDeleteSuggestBlog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BlogHTTPClientImpl) GetAllSuggest(ctx context.Context, in *SearchAllSuggest, opts ...http.CallOption) (*SearchAllReply, error) {
	var out SearchAllReply
	pattern := "/api/getAllSuggest"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBlogGetAllSuggest))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BlogHTTPClientImpl) GetBlogByID(ctx context.Context, in *GetBlogIDRequest, opts ...http.CallOption) (*GetBlogIDReply, error) {
	var out GetBlogIDReply
	pattern := "/api/getId/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBlogGetBlogByID))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BlogHTTPClientImpl) GetBlogByTag(ctx context.Context, in *GetBlogRequest, opts ...http.CallOption) (*GetBlogReply, error) {
	var out GetBlogReply
	pattern := "/api/getTagName/{tag}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBlogGetBlogByTag))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BlogHTTPClientImpl) GetBlogByTitle(ctx context.Context, in *GetBlogByTitleRequest, opts ...http.CallOption) (*GetBlogByTitleReply, error) {
	var out GetBlogByTitleReply
	pattern := "/api/searchBlog/{title}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBlogGetBlogByTitle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BlogHTTPClientImpl) GetCacheBlog(ctx context.Context, in *ListBlogRequest, opts ...http.CallOption) (*ListCacheReply, error) {
	var out ListCacheReply
	pattern := "/api/getCacheBlog"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBlogGetCacheBlog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BlogHTTPClientImpl) ListBlog(ctx context.Context, in *ListBlogRequest, opts ...http.CallOption) (*ListBlogReply, error) {
	var out ListBlogReply
	pattern := "/api/getAllBlog"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBlogListBlog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BlogHTTPClientImpl) UpdateBlog(ctx context.Context, in *UpdateBlogRequest, opts ...http.CallOption) (*UpdateBlogReply, error) {
	var out UpdateBlogReply
	pattern := "/api/updateBlog/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBlogUpdateBlog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BlogHTTPClientImpl) UpdateIndividualFields(ctx context.Context, in *UpdateIndividualFieldsRequest, opts ...http.CallOption) (*UpdateIndividualFieldsReply, error) {
	var out UpdateIndividualFieldsReply
	pattern := "/api/updateIndividual"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBlogUpdateIndividualFields))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BlogHTTPClientImpl) UpdateOnly(ctx context.Context, in *UpdateOnlyRequest, opts ...http.CallOption) (*UpdateOnlyReply, error) {
	var out UpdateOnlyReply
	pattern := "/api/updateOnly"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBlogUpdateOnly))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
